import React, { useEffect, useMemo, useState } from 'react';
import { Factory, Plus, CheckCircle2, AlertTriangle, WifiOff } from 'lucide-react';
import { api } from '../../lib/api';
import { offlineQueue } from '../../lib/offlineQueue';
import { notifyDataChanged } from '../../lib/dataRepository';
import { formatDZD, formatDate, triggerHaptic } from '../../lib/utils';

type Batch = { id:string; batch_number:string; product_name?:string; variant_name?:string; milk_type?:string; milk_input_liters:number; total_cost:number; output_quantity:number; cost_per_unit:number; expiry_date?:string; status:string; notes?:string; variant_id?:string; created_at?:string; _offline?:boolean; _syncOperationId?:string };
type Product = { id:string; name:string; variants?:Array<{id:string;name?:string;unit?:string}> };
const CACHE='azrnou_production_batches_v1';
const money=(v:any)=>formatDZD(Number(v??0));
const mapBatch=(b:any):Batch=>({id:String(b.id),batch_number:b.batch_number??b.batchNumber??String(b.id),product_name:b.product_name??b.productName,variant_name:b.variant_name??b.variantName,milk_type:b.milk_type??b.milkType,milk_input_liters:Number(b.milk_input_liters??b.milkInputLiters??0),total_cost:Number(b.total_cost??b.totalCost??0),output_quantity:Number(b.output_quantity??b.outputQuantity??0),cost_per_unit:Number(b.cost_per_unit??b.costPerUnit??0),expiry_date:b.expiry_date??b.expiryDate,status:b.status??'curing',notes:b.notes,variant_id:b.output_variant_id??b.outputVariantId??b.variant_id??b.variantId,created_at:b.created_at??b.createdAt,_offline:Boolean(b._offline),_syncOperationId:b._syncOperationId});
const readCache=():Batch[]=>{try{return JSON.parse(localStorage.getItem(CACHE)||'[]').map(mapBatch);}catch{return[];}};
const writeCache=(items:Batch[])=>{try{localStorage.setItem(CACHE,JSON.stringify(items));}catch{}};

export const ProductionView: React.FC = () => {
  const [batches,setBatches]=useState<Batch[]>([]); const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [open,setOpen]=useState(false); const [milkType,setMilkType]=useState('goat'); const [milkLiters,setMilkLiters]=useState(120); const [variantId,setVariantId]=useState(''); const [quantity,setQuantity]=useState(80); const [ingredientCost,setIngredientCost]=useState(2500); const [packagingCost,setPackagingCost]=useState(1800); const [curingDays,setCuringDays]=useState(14); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false);
  const load=async()=>{setLoading(true);setError('');try{const [b,p]=await Promise.all([api.productionBatches(),api.products()]);const next=(b.items??[]).map(mapBatch);setBatches(next);writeCache(next);setProducts((p.items??[]).map((x:any)=>({id:String(x.id),name:String(x.name??''),variants:(x.variants??[]).map((v:any)=>({id:String(v.id),name:v.name,unit:v.unit}))})));}catch(e:any){const cached=readCache();if(cached.length){setBatches(cached);setError('Hors ligne : affichage des lots en cache.');}else setError(e.message??'Impossible de charger la production');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const variants=useMemo(()=>products.flatMap(p=>(p.variants??[]).map(v=>({...v,productName:p.name}))),[products]);
  useEffect(()=>{if(!variantId&&variants[0]?.id)setVariantId(variants[0].id);},[variants,variantId]);
  const milkPrice=milkType==='goat'?110:milkType==='cow'?85:milkType==='sheep'?130:100; const totalCost=milkLiters*milkPrice+ingredientCost+packagingCost; const unitCost=quantity>0?Math.round(totalCost/quantity):0;
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!variantId||quantity<=0||milkLiters<=0)return;setSaving(true);setError('');const operationId=crypto.randomUUID();const payload={id:operationId,outputVariantId:variantId,milkType,milkInputLiters:milkLiters,totalCost,outputQuantity:quantity,expiryDate:new Date(Date.now()+(curingDays+45)*86400000).toISOString().slice(0,10),status:'curing',notes:notes.trim()||undefined};try{if(!navigator.onLine)throw new Error('offline');await api.createProductionBatch({...payload,idempotencyKey:operationId});setOpen(false);setNotes('');await load();triggerHaptic();}catch(e:any){const network=!navigator.onLine||/offline|network|failed to fetch|fetch|timeout|connection/i.test(String(e?.message??e));if(!network){setError(e.message??'Erreur de création');}else{const variant=variants.find(v=>v.id===variantId);const local:Batch={id:operationId,batch_number:`OFF-${operationId.slice(0,8).toUpperCase()}`,product_name:(variant as any)?.productName??'Produit',variant_name:(variant as any)?.name,variant_id:variantId,milk_type:milkType,milk_input_liters:milkLiters,total_cost:totalCost,output_quantity:quantity,cost_per_unit:unitCost,expiry_date:payload.expiryDate,status:'curing',notes:payload.notes,created_at:new Date().toISOString(),_offline:true,_syncOperationId:operationId};const next=[local,...batches];setBatches(next);writeCache(next);offlineQueue.enqueue('production','create',payload);notifyDataChanged();setOpen(false);setNotes('');setError('Hors ligne : le lot a été enregistré localement et sera synchronisé automatiquement.');triggerHaptic();}}finally{setSaving(false);}};
  const complete=async(batch:Batch)=>{if(batch._offline){setError('Ce lot hors ligne doit être synchronisé avant sa libération.');return;}if(!batch.variant_id){setError('Ce lot n’a pas de variante de sortie enregistrée.');return;}try{const completionKey=crypto.randomUUID();await api.completeProductionBatch(batch.id,batch.variant_id,completionKey);await load();triggerHaptic();}catch(e:any){setError(e.message??'Impossible de libérer le lot');}};
  const curing=batches.filter(b=>b.status==='curing'); const ready=batches.filter(b=>b.status==='completed'); const liters=batches.reduce((s,b)=>s+b.milk_input_liters,0);
  return <div className="space-y-6 pb-12 animate-fade-in">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2"><Factory className="w-6 h-6 text-emerald-700"/>Fabrication & Lots de Fromagerie</h1><p className="text-xs sm:text-sm text-slate-500 mt-1">Lait → fabrication → affinage → coût de revient → stock</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 px-4 py-2.5 bg-emerald-800 text-white text-xs font-bold rounded-2xl"><Plus className="w-4 h-4"/>Nouveau Lot</button></div>
    {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-xs flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0"/>{error}</div>}
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[['En affinage',curing.length],['Prêts à vendre',ready.length],['Lait transformé',`${liters} L`]].map(([label,value])=><div key={String(label)} className="p-4 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><span className="text-xs text-slate-500">{label}</span><strong className="text-2xl block mt-1 text-slate-900 dark:text-white">{value}</strong></div>)}</div>
    <div className="space-y-3"><h2 className="text-xs font-bold text-slate-500 uppercase">Historique des lots ({batches.length})</h2>{loading?<div className="p-8 text-center text-sm text-slate-500">Chargement des lots depuis le serveur…</div>:batches.length===0?<div className="p-8 text-center text-sm text-slate-500 bg-white rounded-2xl">Aucun lot de fabrication.</div>:batches.map(b=><div key={b.id} className="p-5 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 space-y-4"><div className="flex flex-col sm:flex-row justify-between gap-2"><div><div className="flex items-center gap-2"><h3 className="font-extrabold text-slate-900 dark:text-white">{b.batch_number}</h3><span className={`text-[10px] font-bold px-2 py-1 rounded-full ${b._offline?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-800'}`}>{b._offline?'En attente de sync':b.status==='curing'?'En affinage':'Prêt à la vente'}</span></div><span className="text-xs text-slate-600 dark:text-slate-300">{b.product_name??'Produit'}{b.variant_name?` · ${b.variant_name}`:''} · {b.output_quantity}</span></div><div className="text-right"><span className="text-xs text-slate-400 block">Coût unitaire</span><strong className="text-emerald-800">{money(b.cost_per_unit)}</strong></div></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-3 bg-slate-50 dark:bg-slate-700/40 rounded-2xl text-xs"><div><span className="text-slate-400 block">Lait</span><strong>{b.milk_input_liters} L ({b.milk_type})</strong></div><div><span className="text-slate-400 block">Coût total</span><strong>{money(b.total_cost)}</strong></div><div><span className="text-slate-400 block">Créé</span><strong>{formatDate(b.created_at??'')}</strong></div><div><span className="text-slate-400 block">DLC</span><strong>{formatDate(b.expiry_date??'')}</strong></div></div>{b._offline?<div className="pt-2 border-t text-xs text-amber-700 flex items-center gap-2"><WifiOff className="w-4 h-4"/>Synchronisation automatique à la reconnexion.</div>:b.status==='curing'&&<div className="flex justify-end pt-2 border-t"><button onClick={()=>complete(b)} className="px-4 py-2 bg-emerald-700 text-white text-xs font-bold rounded-xl flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>Libérer & ajouter au stock</button></div>}</div>)}</div>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60"><div className="bg-white dark:bg-slate-900 rounded-3xl p-6 max-w-xl w-full max-h-[92vh] overflow-y-auto"><h3 className="font-bold text-lg text-slate-900 dark:text-white">Nouveau lot de fabrication</h3><p className="text-xs text-slate-500 mb-4">Online : PostgreSQL. Offline : sauvegarde locale + synchronisation idempotente.</p><form onSubmit={create} className="space-y-4"><div><label className="text-xs font-bold">Variante de sortie</label><select value={variantId} onChange={e=>setVariantId(e.target.value)} className="w-full mt-1 p-3 rounded-xl border">{variants.map(v=><option key={v.id} value={v.id}>{(v as any).productName} — {v.name??v.id}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Type de lait<select value={milkType} onChange={e=>setMilkType(e.target.value)} className="w-full mt-1 p-3 rounded-xl border"><option value="goat">Chèvre</option><option value="cow">Vache</option><option value="sheep">Brebis</option><option value="mixed">Mixte</option></select></label><label className="text-xs font-bold">Litres<input type="number" min="1" value={milkLiters} onChange={e=>setMilkLiters(Number(e.target.value))} className="w-full mt-1 p-3 rounded-xl border"/></label><label className="text-xs font-bold">Quantité produite<input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="w-full mt-1 p-3 rounded-xl border"/></label><label className="text-xs font-bold">Affinage (jours)<input type="number" min="0" value={curingDays} onChange={e=>setCuringDays(Number(e.target.value))} className="w-full mt-1 p-3 rounded-xl border"/></label><label className="text-xs font-bold">Ingrédients<input type="number" min="0" value={ingredientCost} onChange={e=>setIngredientCost(Number(e.target.value))} className="w-full mt-1 p-3 rounded-xl border"/></label><label className="text-xs font-bold">Emballage<input type="number" min="0" value={packagingCost} onChange={e=>setPackagingCost(Number(e.target.value))} className="w-full mt-1 p-3 rounded-xl border"/></label></div><div className="p-4 rounded-2xl bg-emerald-50 text-sm">Coût total estimé : <strong>{money(totalCost)}</strong> · Coût unitaire : <strong>{money(unitCost)}</strong></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes" className="w-full p-3 rounded-xl border min-h-20"/><div className="flex gap-2 justify-end"><button type="button" onClick={()=>setOpen(false)} className="px-4 py-2 rounded-xl border">Annuler</button><button disabled={saving||!variantId} className="px-4 py-2 rounded-xl bg-emerald-800 text-white font-bold">{saving?'Enregistrement…':'Créer le lot'}</button></div></form></div></div>}
  </div>;
};
