import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,Droplets,PackageSearch,RefreshCw,Users} from 'lucide-react';
import {api} from '../../lib/api';
import {formatDZD} from '../../lib/utils';

type Tab='profitability'|'customers'|'milk'|'stock';
const today=()=>new Date().toISOString().slice(0,10); const monthStart=()=>{const d=new Date();d.setDate(1);return d.toISOString().slice(0,10);}; const num=(v:any)=>Number(v??0); const money=(v:any)=>formatDZD(num(v));

export const ReportsView:React.FC=()=>{
 const [tab,setTab]=useState<Tab>('profitability'); const [start,setStart]=useState(monthStart()); const [end,setEnd]=useState(today()); const [summary,setSummary]=useState<any>(); const [sales,setSales]=useState<any[]>([]); const [customers,setCustomers]=useState<any[]>([]); const [milk,setMilk]=useState<any>(); const [stock,setStock]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [s,p,c,m,sv]=await Promise.all([api.reportSummary(start,end),api.reportSalesByProduct(start,end),api.reportCustomers(),api.reportMilkYield(start,end),api.reportStockValuation()]);setSummary(s);setSales(p.items??[]);setCustomers(c.items??[]);setMilk(m);setStock(sv.items??[]);}catch(e:any){setError(e?.message??'Impossible de charger les rapports');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const stockValue=useMemo(()=>stock.reduce((s,x)=>s+num(x.valuation),0),[stock]);
 const tabs:[[Tab,string,React.ComponentType<any>],[Tab,string,React.ComponentType<any>],[Tab,string,React.ComponentType<any>],[Tab,string,React.ComponentType<any>]]=[['profitability','Rentabilité',BarChart3],['customers','Clients',Users],['milk','Rendement laitier',Droplets],['stock','Valorisation stock',PackageSearch]];
 return <div className="space-y-6 pb-12 animate-fade-in">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2"><BarChart3 className="w-6 h-6 text-emerald-700"/>Rapports & Analyse</h1><p className="text-xs sm:text-sm text-slate-500 mt-1">Données PostgreSQL réelles, filtrées par période et entreprise.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-[11px] font-bold text-slate-500">Du<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="block mt-1 px-3 py-2 rounded-xl border"/></label><label className="text-[11px] font-bold text-slate-500">Au<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="block mt-1 px-3 py-2 rounded-xl border"/></label><button onClick={()=>void load()} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-800 text-white text-xs font-bold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Actualiser</button></div></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-xs">{error}</div>}
  {summary&&<div className="grid grid-cols-2 lg:grid-cols-6 gap-3"><Metric label="CA" value={money(summary.sales?.revenue)}/><Metric label="Coût ventes" value={money(summary.sales?.cost)}/><Metric label="Marge brute" value={money(summary.sales?.grossMargin)}/><Metric label="Dépenses" value={money(summary.expenses)}/><Metric label="Bénéfice net" value={money(summary.netProfit)}/><Metric label="Flux trésorerie" value={money(summary.cashFlow)}/></div>}
  <div className="flex gap-2 overflow-x-auto no-scrollbar">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={`px-4 py-2 rounded-2xl text-xs font-bold flex items-center gap-2 whitespace-nowrap ${tab===key?'bg-emerald-800 text-white':'bg-white dark:bg-slate-800 border text-slate-600'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>
  {loading&&!summary?<div className="p-10 text-center text-sm text-slate-500">Chargement des rapports…</div>:tab==='profitability'?<ReportTable title="Rentabilité par variante" headers={['Produit','Unités','CA','Coût','Bénéfice','Marge']} rows={sales.map(x=>[x.name,`${num(x.quantity)} ${x.unit??''}`,money(x.revenue),money(x.cost),money(x.profit),`${x.revenue?Math.round(num(x.profit)/num(x.revenue)*100):0}%`])}/>:tab==='customers'?<ReportTable title="Clients & créances" headers={['Client','Commandes','Dépensé','Créance']} rows={customers.map(x=>[x.name,num(x.order_count),money(x.total_spent),money(x.outstanding_balance)])}/>:tab==='milk'?<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Lots" value={num(milk?.batches)}/><Metric label="Lait transformé" value={`${num(milk?.milk_liters)} L`}/><Metric label="Production" value={num(milk?.output_quantity)}/><Metric label="L/L unité" value={num(milk?.liters_per_output_unit).toFixed(2)}/></div>:<><Metric label="Valeur stock disponible" value={money(stockValue)}/><ReportTable title="Stock valorisé" headers={['Produit','SKU','Disponible','Coût unitaire','Valeur']} rows={stock.map(x=>[x.name,x.sku??'—',num(x.available),money(x.production_cost),money(x.valuation)])}/></>}
 </div>;
};
const Metric=({label,value}:{label:string;value:React.ReactNode})=><div className="p-4 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><span className="text-[11px] text-slate-500 block">{label}</span><strong className="text-xl block mt-1 text-slate-900 dark:text-white">{value}</strong></div>;
const ReportTable=({title,headers,rows}:{title:string;headers:string[];rows:React.ReactNode[][]})=><div className="bg-white dark:bg-slate-800 rounded-3xl border border-slate-200 dark:border-slate-700 overflow-hidden"><div className="p-5 border-b"><h3 className="font-bold text-slate-900 dark:text-white">{title}</h3></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="bg-slate-50 dark:bg-slate-700/50">{headers.map(h=><th key={h} className="px-4 py-3 text-left font-bold text-slate-500">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t border-slate-100 dark:border-slate-700">{row.map((cell,j)=><td key={j} className="px-4 py-3 text-slate-700 dark:text-slate-200">{cell}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="px-4 py-10 text-center text-slate-500">Aucune donnée pour cette période.</td></tr>}</tbody></table></div></div>;
