import React, { useEffect, useMemo, useState } from 'react';
import { X, ShoppingBag, Truck, FileText, CheckCircle2, Clock, Download, DollarSign, MessageSquare } from 'lucide-react';
import { Order, OrderStatus } from '../../types';
import { formatDZD, formatDate, generateWhatsAppLink } from '../../lib/utils';
import { StatusBadge } from '../common/Badge';
import { dataRepository } from '../../lib/dataRepository';
import { api } from '../../lib/api';
import { db } from '../../lib/storage';
import { downloadDocumentPDF, DocumentData } from '../../lib/pdfGenerator';

interface OrderDetailModalProps { orderId: string; isOpen: boolean; onClose: () => void; onUpdate: () => void; }

export const OrderDetailModal: React.FC<OrderDetailModalProps> = ({ orderId, isOpen, onClose, onUpdate }) => {
  const [order, setOrder] = useState<Order | null>(null);
  const [loading, setLoading] = useState(true);
  const [payAmount, setPayAmount] = useState(0);
  const [showPayment, setShowPayment] = useState(false);
  const [showDelivery, setShowDelivery] = useState(false);
  const [deliveryQuantities, setDeliveryQuantities] = useState<Record<string, number>>({});
  const settings = db.getSettings();

  const refresh = async () => { try { const result = await dataRepository.orders(); setOrder(result.items.find(x => x.id === orderId) ?? null); } catch (error) { console.error(error); } finally { setLoading(false); } };
  useEffect(() => { if (isOpen) void refresh(); }, [isOpen, orderId]);

  const remainingItems = useMemo(() => order?.items.map(item => ({ ...item, remaining: Math.max(0, item.quantity - item.deliveredQuantity) })).filter(item => item.remaining > 0) ?? [], [order]);

  if (!isOpen) return null;
  if (loading) return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60"><div className="bg-white dark:bg-slate-900 rounded-3xl p-8 text-sm text-slate-500">Chargement de la commande...</div></div>;
  if (!order) return null;

  const handleStatusChange = async (status: OrderStatus) => { try { await api.updateOrderStatus(order.id, status); await refresh(); onUpdate(); } catch (error: any) { alert(error.message); } };
  const handlePayment = async (e: React.FormEvent) => { e.preventDefault(); if (payAmount <= 0) return; try { await api.createPayment({ orderId: order.id, amount: payAmount, method: 'cash', note: `Règlement pour commande ${order.orderNumber}`, idempotencyKey: `order-payment:${order.id}:${Date.now()}` }); setShowPayment(false); setPayAmount(0); await refresh(); onUpdate(); } catch (error: any) { alert(error.message); } };
  const handleInvoice = async () => { try { const inv: any = await api.createInvoiceFromOrder(order.id); alert(`Facture générée avec succès : ${inv.number ?? inv.invoice_number ?? 'FAC'}`); await refresh(); onUpdate(); } catch (error: any) { alert(error.message); } };
  const handleDelivery = async () => { try { const items = remainingItems.map(item => ({ variantId: item.variantId, quantity: Number(deliveryQuantities[item.variantId] ?? item.remaining) })).filter(item => item.quantity > 0); if (!items.length) return alert('Sélectionnez au moins une quantité à livrer.'); await api.createDelivery({ orderId: order.id, items, deliveryDate: new Date().toISOString().slice(0,10), address: '' }); setShowDelivery(false); await refresh(); onUpdate(); } catch (error: any) { alert(error.message); } };
  const handleDownload = () => { const data: DocumentData = { type: 'order', documentNumber: order.orderNumber, date: order.createdAt, deliveryDate: order.deliveryDate, customerName: order.customerName, customerPhone: order.customerPhone, items: order.items.map(i => ({ designation: i.productName, quantity: i.quantity, unit: i.unit, unitPrice: i.unitPrice, total: i.subtotal })), subtotal: order.subtotal, discount: order.discount, total: order.total, paidAmount: order.paidAmount, balanceRemaining: Math.max(0, order.total - order.paidAmount), notes: order.notes }; downloadDocumentPDF(data, settings); };
  const handleWhatsApp = () => { window.open(generateWhatsAppLink(order.customerPhone, `Bonjour ${order.customerName},\nVoici les détails de votre commande AZRNOU (${order.orderNumber}) :\nMontant total : ${formatDZD(order.total)}\nDate prévue : ${order.deliveryDate}\nMerci pour votre confiance !`), '_blank'); };

  return <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in overflow-y-auto"><div className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col my-8 max-h-[92vh]">
    <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800 shrink-0"><div className="flex items-center gap-3"><div className="p-2 rounded-xl bg-emerald-50 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-400"><ShoppingBag className="w-5 h-5" /></div><div><div className="flex items-center gap-2"><h2 className="text-lg font-extrabold text-slate-900 dark:text-white">{order.orderNumber}</h2><StatusBadge status={order.status} size="sm" /></div><span className="text-xs text-slate-500">Créée le {formatDate(order.createdAt, true)}</span></div></div><div className="flex items-center gap-2"><button type="button" onClick={handleWhatsApp} className="p-2 rounded-xl text-emerald-700 hover:bg-emerald-50"><MessageSquare className="w-5 h-5" /></button><button type="button" onClick={handleDownload} className="p-2 rounded-xl text-slate-600 hover:bg-slate-100"><Download className="w-5 h-5" /></button><button type="button" onClick={onClose} className="p-2 rounded-xl text-slate-400 hover:bg-slate-100"><X className="w-5 h-5" /></button></div></div>
    <div className="p-6 space-y-6 overflow-y-auto flex-1">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700"><div><span className="text-[11px] font-bold text-slate-400 uppercase block mb-1">Client</span><span className="text-sm font-bold text-slate-900 dark:text-white block">{order.customerName}</span><span className="text-xs text-slate-500">{order.customerPhone}</span></div><div><span className="text-[11px] font-bold text-slate-400 uppercase block mb-1">Livraison</span><span className="text-sm font-bold text-slate-900 dark:text-white block">Prévue : {formatDate(order.deliveryDate)}</span>{order.notes && <span className="text-xs text-amber-700 block mt-1">Note: {order.notes}</span>}</div></div>
      <div><span className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase block mb-2">Étape du cycle</span><div className="flex flex-wrap gap-2">{order.status === 'confirmed' && <button onClick={() => handleStatusChange('preparing')} className="px-3 py-1.5 bg-amber-500 text-white text-xs font-bold rounded-xl flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" />Lancer la préparation</button>}{order.status === 'preparing' && <button onClick={() => handleStatusChange('ready')} className="px-3 py-1.5 bg-teal-600 text-white text-xs font-bold rounded-xl flex items-center gap-1.5"><CheckCircle2 className="w-3.5 h-3.5" />Marquer prête</button>}{remainingItems.length > 0 && <button onClick={() => { setDeliveryQuantities(Object.fromEntries(remainingItems.map(i => [i.variantId, i.remaining]))); setShowDelivery(true); }} className="px-3 py-1.5 bg-emerald-700 text-white text-xs font-bold rounded-xl flex items-center gap-1.5"><Truck className="w-3.5 h-3.5" />Créer BL / Livrer</button>}{!order.invoicedAt && <button onClick={handleInvoice} className="px-3 py-1.5 bg-indigo-600 text-white text-xs font-bold rounded-xl flex items-center gap-1.5"><FileText className="w-3.5 h-3.5" />Générer Facture</button>}</div></div>
      <div><span className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase block mb-2">Produits commandés</span><div className="border border-slate-200 dark:border-slate-700 rounded-2xl overflow-hidden"><table className="w-full text-left text-xs"><thead className="bg-slate-50 dark:bg-slate-800 text-slate-500"><tr><th className="px-4 py-2.5">Produit</th><th className="px-3 py-2.5 text-center">Qté</th><th className="px-3 py-2.5 text-center">Livré</th><th className="px-4 py-2.5 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{order.items.map((item,i) => <tr key={i}><td className="px-4 py-3 font-semibold text-slate-900 dark:text-white">{item.productName}</td><td className="px-3 py-3 text-center">{item.quantity} {item.unit}</td><td className="px-3 py-3 text-center">{item.deliveredQuantity} / {item.quantity}</td><td className="px-4 py-3 text-right font-bold">{formatDZD(item.subtotal)}</td></tr>)}</tbody></table></div></div>
      <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 space-y-3"><div className="flex justify-between text-xs"><span>Total</span><strong>{formatDZD(order.total)}</strong></div><div className="flex justify-between text-xs"><span>Réglé</span><strong>{formatDZD(order.paidAmount)}</strong></div><div className="flex justify-between text-sm"><span className="font-bold text-rose-600">Reste</span><strong className="text-rose-600">{formatDZD(Math.max(0, order.total-order.paidAmount))}</strong></div>{order.total > order.paidAmount && !showPayment && <button onClick={() => { setPayAmount(order.total-order.paidAmount); setShowPayment(true); }} className="w-full py-2 bg-emerald-700 text-white text-xs font-bold rounded-xl flex items-center justify-center gap-1.5"><DollarSign className="w-4 h-4" />Encaisser</button>}{showPayment && <form onSubmit={handlePayment} className="flex gap-2"><input type="number" min="1" max={order.total-order.paidAmount} value={payAmount} onChange={e => setPayAmount(Number(e.target.value)||0)} className="flex-1 px-3 py-2 border rounded-xl text-xs" /><button className="px-4 py-2 bg-emerald-700 text-white text-xs font-bold rounded-xl">Valider</button></form>}</div>
    </div>
    {showDelivery && <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/60"><div className="bg-white dark:bg-slate-900 rounded-3xl p-6 max-w-md w-full"><h3 className="font-bold text-slate-900 dark:text-white mb-4">Livraison / Bon de Livraison</h3><div className="space-y-3">{remainingItems.map(item => <div key={item.variantId} className="flex items-center justify-between gap-3"><span className="text-xs font-semibold">{item.productName}</span><input type="number" min="0" max={item.remaining} value={deliveryQuantities[item.variantId] ?? 0} onChange={e => setDeliveryQuantities(prev => ({ ...prev, [item.variantId]: Number(e.target.value)||0 }))} className="w-24 px-2 py-2 border rounded-xl text-xs text-right" /></div>)}</div><div className="flex justify-end gap-2 mt-5"><button onClick={() => setShowDelivery(false)} className="px-4 py-2 text-xs rounded-xl">Annuler</button><button onClick={handleDelivery} className="px-5 py-2 bg-emerald-700 text-white text-xs font-bold rounded-xl">Créer BL</button></div></div></div>}
  </div></div>;
};
