import { Router } from 'express';
import { query, transaction } from '../db.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router = Router();
router.use(requireAuth);

router.get('/customers', async (_req,res,next)=>{try{const r=await query(`SELECT c.*,COALESCE(o.total_purchases,0) total_purchases,COALESCE(o.total_paid,0) total_paid,COALESCE(o.outstanding_balance,0) outstanding_balance FROM customers c LEFT JOIN (SELECT customer_id,SUM(total) total_purchases,SUM(paid_total) total_paid,SUM(total-paid_total) outstanding_balance FROM orders WHERE status<>'cancelled' GROUP BY customer_id) o ON o.customer_id=c.id WHERE c.active=true ORDER BY c.name`);res.json({items:r.rows});}catch(e){next(e);}});
router.post('/customers',requireRole('owner','manager','worker'),async(req,res,next)=>{try{const name=String(req.body?.name??'').trim();if(!name)return res.status(400).json({error:'Customer name is required'});const r=await query(`INSERT INTO customers(name,phone,address,notes,type,credit_limit,payment_terms_days,custom_prices) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[name,req.body?.phone??null,req.body?.address??null,req.body?.notes??null,req.body?.type??'wholesale',Number(req.body?.creditLimit??0),Number(req.body?.paymentTermsDays??0),req.body?.customPrices??{}]);const row=r.rows[0] as Record<string,unknown>;res.status(201).json({...row,total_purchases:0,total_paid:0,outstanding_balance:0});}catch(e){next(e);}});

router.get('/products',async(_req,res,next)=>{try{const r=await query(`SELECT p.*,COALESCE(json_agg(json_build_object('id',v.id,'name',v.name,'sku',v.sku,'unit',v.unit,'retail_price',v.retail_price,'wholesale_price',v.wholesale_price,'cost',v.cost,'min_stock',v.min_stock,'current_stock',COALESCE(b.quantity,0),'reserved_stock',COALESCE(b.reserved_quantity,0)) ORDER BY v.created_at) FILTER (WHERE v.id IS NOT NULL),'[]') variants FROM products p LEFT JOIN product_variants v ON v.product_id=p.id AND v.active=true LEFT JOIN inventory_balances b ON b.variant_id=v.id WHERE p.active=true GROUP BY p.id ORDER BY p.name`);res.json({items:r.rows});}catch(e){next(e);}});
router.post('/products',requireRole('owner','manager','worker'),async(req,res,next)=>{try{const result=await transaction(async client=>{const p=await client.query(`INSERT INTO products(name,category_id,description,active) VALUES($1,$2,$3,true) RETURNING *`,[String(req.body?.name??'').trim(),req.body?.categoryId??null,req.body?.description??null]);const v=await client.query(`INSERT INTO product_variants(product_id,name,sku,unit,retail_price,wholesale_price,cost,min_stock,min_order_qty,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true) RETURNING *`,[p.rows[0].id,req.body?.variantName??p.rows[0].name,req.body?.sku??`SKU-${Date.now()}`,req.body?.unit??'piece',Number(req.body?.retailPrice??0),Number(req.body?.wholesalePrice??0),Number(req.body?.cost??0),Number(req.body?.minStock??0),Number(req.body?.minOrderQty??1)]);return {...p.rows[0],variants:[v.rows[0]]};});res.status(201).json(result);}catch(e){next(e);}});

router.post('/orders',requireRole('owner','manager','worker'),async(req,res,next)=>{try{const result=await transaction(async client=>{const items=Array.isArray(req.body?.items)?req.body.items:[];if(!items.length)throw Object.assign(new Error('Order items are required'),{status:400});let subtotal=0,costTotal=0;for(const item of items){const v=await client.query(`SELECT id,retail_price,cost FROM product_variants WHERE id=$1 AND active=true`,[item.variantId]);if(!v.rows[0])throw Object.assign(new Error('Variant not found'),{status:404});const q=Number(item.quantity);if(q<=0)throw Object.assign(new Error('Invalid quantity'),{status:400});subtotal+=q*Number(item.unitPrice??v.rows[0].retail_price);costTotal+=q*Number(v.rows[0].cost);}const discount=Number(req.body?.discount??0),total=subtotal-discount;const o=await client.query(`INSERT INTO orders(customer_id,order_number,status,subtotal,discount,total,cost_total,paid_total,payment_status,order_date) VALUES($1,$2,'confirmed',$3,$4,$5,$6,0,'unpaid',NOW()) RETURNING *`,[req.body?.customerId??null,req.body?.orderNumber??`CMD-${Date.now()}`,subtotal,discount,total,costTotal]);for(const item of items){const q=Number(item.quantity);const v=await client.query(`SELECT id,retail_price,cost FROM product_variants WHERE id=$1`,[item.variantId]);const price=Number(item.unitPrice??v.rows[0].retail_price);await client.query(`INSERT INTO order_items(order_id,variant_id,quantity,unit_price,unit_cost,discount) VALUES($1,$2,$3,$4,$5,$6)`,[o.rows[0].id,item.variantId,q,price,Number(v.rows[0].cost),Number(item.discount??0)]);await client.query(`UPDATE inventory_balances SET reserved_quantity=reserved_quantity+$2,updated_at=NOW() WHERE variant_id=$1 AND quantity-reserved_quantity >= $2`,[item.variantId,q]);}return o.rows[0];});res.status(201).json(result);}catch(e){next(e);}});

router.post('/payments',requireRole('owner','manager'),async(req,res,next)=>{try{const result=await transaction(async client=>{const amount=Number(req.body?.amount);if(amount<=0)throw Object.assign(new Error('Invalid payment amount'),{status:400});const order=await client.query(`SELECT * FROM orders WHERE id=$1 FOR UPDATE`,[req.body?.orderId]);if(!order.rows[0])throw Object.assign(new Error('Order not found'),{status:404});if(amount>Number(order.rows[0].total)-Number(order.rows[0].paid_total))throw Object.assign(new Error('Payment exceeds outstanding balance'),{status:400});const p=await client.query(`INSERT INTO payments(order_id,amount,payment_method,payment_date,notes,idempotency_key) VALUES($1,$2,$3,NOW(),$4,$5) RETURNING *`,[req.body.orderId,amount,req.body?.method??'cash',req.body?.notes??null,req.body?.idempotencyKey??`payment:${req.body.orderId}:${Date.now()}`]);const paid=Number(order.rows[0].paid_total)+amount;await client.query(`UPDATE orders SET paid_total=$2,payment_status=CASE WHEN $2>=total THEN 'paid' ELSE 'partial' END,updated_at=NOW() WHERE id=$1`,[req.body.orderId,paid]);return p.rows[0];});res.status(201).json(result);}catch(e){next(e);}});
export default router;
