import { Router } from 'express';
import { query, transaction } from '../db.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router=Router(); router.use(requireAuth);
async function nextNumber(client: import('pg').PoolClient){const row=await client.query<{value:{counter?:number}}>('SELECT value FROM app_settings WHERE key=$1 FOR UPDATE',['batch_number']);const n=Number(row.rows[0]?.value?.counter??0)+1;await client.query(`INSERT INTO app_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()`,['batch_number',JSON.stringify({counter:n})]);return `LOT-${String(n).padStart(6,'0')}`;}
router.get('/batches',async(_req,res,next)=>{try{const r=await query(`SELECT pb.*,p.name AS product_name FROM production_batches pb LEFT JOIN products p ON p.id=pb.product_id ORDER BY pb.created_at DESC`);res.json({items:r.rows});}catch(e){next(e);}});
router.post('/batches',requireRole('owner','manager','worker'),async(req,res,next)=>{try{const milk=Number(req.body?.milkInputLiters??0), output=Number(req.body?.outputQuantity??0), cost=Number(req.body?.totalCost??0); if(milk<=0||output<=0||cost<0||!req.body?.outputVariantId) return res.status(400).json({error:'Milk input, output quantity, cost and output variant are required'}); const result=await transaction(async client=>{const number=await nextNumber(client); const b=await client.query(`INSERT INTO production_batches(batch_number,product_id,milk_type,milk_input_liters,total_cost,output_quantity,cost_per_unit,expiry_date,status,notes,created_by) VALUES($1,(SELECT product_id FROM product_variants WHERE id=$2),$3,$4,$5,$6,$7,$8,'completed',$9,$10) RETURNING *`,[number,req.body.outputVariantId,req.body?.milkType??null,milk,cost,output,cost/output,req.body?.expiryDate??null,req.body?.notes??null,req.user!.id]); await client.query(`INSERT INTO inventory_balances(variant_id,quantity,reserved_quantity) VALUES($1,$2,0) ON CONFLICT(variant_id) DO UPDATE SET quantity=inventory_balances.quantity+$2,updated_at=NOW()`,[req.body.outputVariantId,output]); await client.query(`INSERT INTO inventory_movements(variant_id,movement_type,quantity,reference_type,reference_id,idempotency_key,created_by) VALUES($1,'production',$2,'production',$3,$4,$5)`,[req.body.outputVariantId,output,b.rows[0].id,`production:${b.rows[0].id}:${req.body.outputVariantId}`,req.user!.id]); return b.rows[0];});res.status(201).json(result);}catch(e){next(e);}});
router.get('/livestock',async(_req,res,next)=>{try{const r=await query(`SELECT animal_type,COALESCE(SUM(CASE WHEN event_type IN ('purchase','birth') THEN quantity WHEN event_type IN ('sale','death','loss') THEN -quantity ELSE 0 END),0) AS current_count,COALESCE(SUM(CASE WHEN event_type IN ('feed','veterinary','medicine') THEN COALESCE(amount,0) ELSE 0 END),0) AS care_cost FROM livestock_events GROUP BY animal_type ORDER BY animal_type`);res.json({items:r.rows});}catch(e){next(e);}});
router.post('/livestock/events',requireRole('owner','manager','worker'),async(req,res,next)=>{try{const type=String(req.body?.eventType??''),animal=String(req.body?.animalType??''),q=Number(req.body?.quantity);if(!['purchase','sale','birth','death','loss','feed','veterinary','medicine','other'].includes(type)||!['cow','goat'].includes(animal)||!Number.isFinite(q)||q<=0)return res.status(400).json({error:'Invalid livestock event'});const r=await query(`INSERT INTO livestock_events(event_type,animal_type,quantity,amount,event_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[type,animal,q,Number(req.body?.amount??0),req.body?.date??new Date().toISOString().slice(0,10),req.body?.notes??null,req.user!.id]);res.status(201).json(r.rows[0]);}catch(e){next(e);}});
router.post('/feed',requireRole('owner','manager','worker'),async(req,res,next)=>{try{const q=Number(req.body?.quantity),cost=Number(req.body?.cost??0);if(!Number.isFinite(q)||q<=0||!Number.isFinite(cost)||cost<0)return res.status(400).json({error:'Invalid feed record'});const r=await query(`INSERT INTO feed_records(animal_type,quantity,unit,cost,supplier_id,record_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.body?.animalType??'mixed',q,String(req.body?.unit??'kg'),cost,req.body?.supplierId??null,req.body?.date??new Date().toISOString().slice(0,10),req.body?.notes??null,req.user!.id]);res.status(201).json(r.rows[0]);}catch(e){next(e);}});
export default router;
