import { Router } from 'express';
import { query } from '../db.js';
import { requireAuth } from '../middleware/auth.js';

const router=Router(); router.use(requireAuth);
router.get('/summary',async(req,res,next)=>{try{const start=String(req.query.start??'1970-01-01'),end=String(req.query.end??'2999-12-31');const [sales,expenses,purchases,stock,debts]=await Promise.all([query(`SELECT COALESCE(SUM(total),0) AS revenue,COALESCE(SUM(cost_total),0) AS cost,COALESCE(SUM(paid_total),0) AS collected FROM orders WHERE status<>'cancelled' AND created_at::date BETWEEN $1 AND $2`,[start,end]),query(`SELECT COALESCE(SUM(amount),0) AS total FROM expenses WHERE expense_date BETWEEN $1 AND $2`,[start,end]),query(`SELECT COALESCE(SUM(total),0) AS total,COALESCE(SUM(paid_total),0) AS paid FROM purchases WHERE status<>'cancelled' AND purchase_date BETWEEN $1 AND $2`,[start,end]),query(`SELECT COUNT(*)::int AS variants,COALESCE(SUM(quantity),0) AS units,COALESCE(SUM(reserved_quantity),0) AS reserved,COALESCE(SUM(quantity-reserved_quantity),0) AS available FROM inventory_balances`),query(`SELECT COALESCE(SUM(total-paid_total),0) AS outstanding FROM orders WHERE status<>'cancelled'`)]);const s=sales.rows[0],e=expenses.rows[0],p=purchases.rows[0];const gross=Number(s.revenue)-Number(s.cost),net=gross-Number(e.total);res.json({period:{start,end},sales:{revenue:Number(s.revenue),cost:Number(s.cost),collected:Number(s.collected),grossMargin:gross},expenses:Number(e.total),purchases:{total:Number(p.total),paid:Number(p.paid)},netProfit:net,inventory:stock.rows[0],customerOutstanding:Number(debts.rows[0].outstanding)});}catch(e){next(e);}});
router.get('/sales-by-product',async(req,res,next)=>{try{const start=String(req.query.start??'1970-01-01'),end=String(req.query.end??'2999-12-31');const r=await query(`SELECT oi.variant_id,v.name,COALESCE(SUM(oi.quantity),0) AS quantity,COALESCE(SUM(oi.quantity*oi.unit_price-oi.discount),0) AS revenue,COALESCE(SUM(oi.quantity*oi.unit_cost),0) AS cost FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN product_variants v ON v.id=oi.variant_id WHERE o.status<>'cancelled' AND o.created_at::date BETWEEN $1 AND $2 GROUP BY oi.variant_id,v.name ORDER BY revenue DESC`,[start,end]);res.json({items:r.rows});}catch(e){next(e);}});
router.get('/low-stock',async(_req,res,next)=>{try{const r=await query(`SELECT v.id,v.name,v.sku,b.quantity,b.reserved_quantity,b.quantity-b.reserved_quantity AS available,v.min_stock FROM product_variants v JOIN inventory_balances b ON b.variant_id=v.id WHERE v.active=TRUE AND b.quantity-b.reserved_quantity<=v.min_stock ORDER BY available ASC`);res.json({items:r.rows});}catch(e){next(e);}});
export default router;
