import { Router } from 'express';
import { query } from '../db.js';
import { requireAuth } from '../middleware/auth.js';

const router=Router();
router.use(requireAuth);

type SummarySales={revenue:number;cost:number;collected:number}; type SummaryExpense={total:number}; type SummaryPurchase={total:number;paid:number}; type SummaryStock={variants:number;units:number;reserved:number;available:number;valuation:number}; type SummaryDebt={outstanding:number}; type SummaryCash={incoming:number;expenses:number;purchases_paid:number};

router.get('/summary',async(req,res,next)=>{try{const start=String(req.query.start??'1970-01-01'),end=String(req.query.end??'2999-12-31');const [sales,expenses,purchases,stock,debts,cash]=await Promise.all([
query<SummarySales>(`SELECT COALESCE(SUM(total),0)::numeric revenue,COALESCE(SUM(cost_total),0)::numeric cost,COALESCE(SUM(paid_total),0)::numeric collected FROM orders WHERE status<>'cancelled' AND created_at::date BETWEEN $1 AND $2`,[start,end]),
query<SummaryExpense>(`SELECT COALESCE(SUM(amount),0)::numeric total FROM expenses WHERE expense_date BETWEEN $1 AND $2`,[start,end]),
query<SummaryPurchase>(`SELECT COALESCE(SUM(total),0)::numeric total,COALESCE(SUM(paid_total),0)::numeric paid FROM purchases WHERE status<>'cancelled' AND purchase_date BETWEEN $1 AND $2`,[start,end]),
query<SummaryStock>(`SELECT COUNT(*)::int variants,COALESCE(SUM(quantity),0)::numeric units,COALESCE(SUM(reserved_quantity),0)::numeric reserved,COALESCE(SUM(quantity-reserved_quantity),0)::numeric available,COALESCE(SUM((quantity-reserved_quantity)*v.production_cost),0)::numeric valuation FROM inventory_balances b JOIN product_variants v ON v.id=b.variant_id WHERE v.active=TRUE`),
query<SummaryDebt>(`SELECT COALESCE(SUM(total-paid_total),0)::numeric outstanding FROM orders WHERE status<>'cancelled'`),
query<SummaryCash>(`SELECT COALESCE((SELECT SUM(amount) FROM payments WHERE created_at::date BETWEEN $1 AND $2),0)::numeric incoming,COALESCE((SELECT SUM(amount) FROM expenses WHERE expense_date BETWEEN $1 AND $2),0)::numeric expenses,COALESCE((SELECT SUM(paid_total) FROM purchases WHERE purchase_date BETWEEN $1 AND $2),0)::numeric purchases_paid`,[start,end])
]);const s=sales.rows[0],e=expenses.rows[0],p=purchases.rows[0],c=cash.rows[0];const gross=Number(s.revenue)-Number(s.cost);const net=gross-Number(e.total);res.json({period:{start,end},sales:{revenue:Number(s.revenue),cost:Number(s.cost),collected:Number(s.collected),grossMargin:gross},expenses:Number(e.total),purchases:{total:Number(p.total),paid:Number(p.paid)},cashFlow:Number(c.incoming)-Number(c.expenses)-Number(c.purchases_paid),netProfit:net,inventory:stock.rows[0],customerOutstanding:Number(debts.rows[0].outstanding)});}catch(e){next(e);}});
router.get('/sales-by-product',async(req,res,next)=>{try{const start=String(req.query.start??'1970-01-01'),end=String(req.query.end??'2999-12-31');const r=await query(`SELECT oi.variant_id,v.name,v.unit,COALESCE(SUM(oi.quantity),0)::numeric quantity,COALESCE(SUM(oi.quantity*oi.unit_price-oi.discount),0)::numeric revenue,COALESCE(SUM(oi.quantity*oi.unit_cost),0)::numeric cost,COALESCE(SUM((oi.quantity*oi.unit_price)-oi.discount-(oi.quantity*oi.unit_cost)),0)::numeric profit FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN product_variants v ON v.id=oi.variant_id WHERE o.status<>'cancelled' AND o.created_at::date BETWEEN $1 AND $2 GROUP BY oi.variant_id,v.name,v.unit ORDER BY profit DESC`,[start,end]);res.json({items:r.rows});}catch(e){next(e);}});
router.get('/customers',async(_req,res,next)=>{try{const r=await query(`SELECT c.id,c.name,c.phone,COUNT(o.id)::int order_count,COALESCE(SUM(o.total),0)::numeric total_spent,GREATEST(COALESCE(SUM(o.total-o.paid_total),0),0)::numeric outstanding_balance FROM customers c LEFT JOIN orders o ON o.customer_id=c.id AND o.status<>'cancelled' WHERE c.active=TRUE GROUP BY c.id,c.name,c.phone ORDER BY total_spent DESC`);res.json({items:r.rows});}catch(e){next(e);}});
router.get('/milk-yield',async(req,res,next)=>{try{const start=String(req.query.start??'1970-01-01'),end=String(req.query.end??'2999-12-31');const r=await query(`SELECT COUNT(*)::int batches,COALESCE(SUM(milk_input_liters),0)::numeric milk_liters,COALESCE(SUM(output_quantity),0)::numeric output_quantity,CASE WHEN COALESCE(SUM(output_quantity),0)=0 THEN 0 ELSE ROUND((SUM(milk_input_liters)/SUM(output_quantity))::numeric,2) END liters_per_output_unit,COALESCE(SUM(total_cost),0)::numeric production_cost FROM production_batches WHERE created_at::date BETWEEN $1 AND $2`,[start,end]);res.json(r.rows[0]);}catch(e){next(e);}});
router.get('/stock-valuation',async(_req,res,next)=>{try{const r=await query(`SELECT v.id,v.name,v.sku,v.unit,v.production_cost,b.quantity,b.reserved_quantity,(b.quantity-b.reserved_quantity)::numeric available,((b.quantity-b.reserved_quantity)*v.production_cost)::numeric valuation FROM product_variants v JOIN inventory_balances b ON b.variant_id=v.id WHERE v.active=TRUE ORDER BY valuation DESC`);res.json({items:r.rows});}catch(e){next(e);}});
router.get('/low-stock',async(_req,res,next)=>{try{const r=await query(`SELECT v.id,v.name,v.sku,b.quantity,b.reserved_quantity,b.quantity-b.reserved_quantity available,v.min_stock FROM product_variants v JOIN inventory_balances b ON b.variant_id=v.id WHERE v.active=TRUE AND b.quantity-b.reserved_quantity<=v.min_stock ORDER BY available ASC`);res.json({items:r.rows});}catch(e){next(e);}});
export default router;
