import { Router } from 'express';
import { query, transaction } from '../db.js';
import { requireAuth } from '../middleware/auth.js';

const router=Router(); router.use(requireAuth);
const allowedEntities=new Set(['customer','supplier','product','variant','order','payment','expense','purchase','production','livestock_event','feed','return','waste']);
router.post('/push',async(req,res,next)=>{try{const deviceId=String(req.body?.deviceId??'').trim(),operations=Array.isArray(req.body?.operations)?req.body.operations:[];if(!deviceId||!operations.length)return res.status(400).json({error:'deviceId and operations are required'});const result=await transaction(async client=>{const accepted:string[]=[],duplicates:string[]=[],rejected:Array<{operationId:string;reason:string}>=[];for(const op of operations){const id=String(op?.operationId??'');const entity=String(op?.entityType??'');if(!id||!allowedEntities.has(entity)){rejected.push({operationId:id,reason:'Unsupported or invalid operation'});continue;}const existing=await client.query('SELECT status FROM sync_operations WHERE operation_id=$1',[id]);if(existing.rows[0]){duplicates.push(id);continue;}await client.query(`INSERT INTO sync_operations(device_id,operation_id,entity_type,entity_id,operation_type,payload,status,applied_at) VALUES($1,$2,$3,$4,$5,$6,'applied',NOW())`,[deviceId,id,entity,op.entityId??null,String(op.operationType??'create'),JSON.stringify(op.payload??{})]);accepted.push(id);}return{accepted,duplicates,rejected};});res.json(result);}catch(e){next(e);}});
router.get('/pull',async(req,res,next)=>{try{const since=String(req.query.since??'1970-01-01T00:00:00.000Z'),deviceId=String(req.query.deviceId??'');const r=await query(`SELECT operation_id,device_id,entity_type,entity_id,operation_type,payload,status,created_at,applied_at FROM sync_operations WHERE created_at>$1 AND ($2='' OR device_id<>$2) ORDER BY created_at ASC LIMIT 500`,[since,deviceId]);res.json({items:r.rows,nextSince:new Date().toISOString()});}catch(e){next(e);}});
router.get('/status',async(req,res,next)=>{try{const deviceId=String(req.query.deviceId??'');const r=await query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='pending')::int AS pending,COUNT(*) FILTER(WHERE status='rejected')::int AS rejected,MAX(created_at) AS last_operation FROM sync_operations WHERE ($1='' OR device_id=$1)`,[deviceId]);res.json(r.rows[0]);}catch(e){next(e);}});
export default router;
