import React, { useEffect, useState } from 'react';
import { X, AlertTriangle, Clock, AlertCircle, DollarSign, CheckCircle2, ArrowRight } from 'lucide-react';
import { formatDZD } from '../../lib/utils';
import { MainTab } from './BottomNav';
import { dataRepository } from '../../lib/dataRepository';

interface NotificationDrawerProps { isOpen:boolean; onClose:()=>void; onNavigate:(tab:MainTab,id?:string)=>void; }
type AlertItem={id:string;type:'low_stock'|'order_due'|'unpaid_balance';title:string;description:string;severity:'urgent'|'warning';tab:MainTab;targetId:string};
export const NotificationDrawer:React.FC<NotificationDrawerProps>=({isOpen,onClose,onNavigate})=>{
 const [alerts,setAlerts]=useState<AlertItem[]>([]);
 useEffect(()=>{if(!isOpen)return;let active=true;const load=async()=>{try{const [p,o,c]=await Promise.all([dataRepository.products(),dataRepository.orders(),dataRepository.customers()]);const today=new Date().toISOString().slice(0,10);const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);const low=p.items.filter(v=>v.active!==false&&Number(v.currentStock??0)<=Number(v.minStock??0)).map(v=>({id:`ls_${v.id}`,type:'low_stock' as const,title:`Stock critique: ${v.name}`,description:`Stock actuel: ${v.currentStock??0} ${v.unit??''} (Seuil min: ${v.minStock??0})`,severity:'urgent' as const,tab:'products' as MainTab,targetId:v.id}));const due=o.items.filter(x=>['confirmed','preparing','ready'].includes(String(x.status))&&(String(x.deliveryDate??'').slice(0,10)===today||String(x.deliveryDate??'').slice(0,10)===tomorrow)).map(x=>({id:`ord_${x.id}`,type:'order_due' as const,title:`Commande à livrer ${String(x.deliveryDate).slice(0,10)===today?"aujourd'hui":'demain'}`,description:`${x.orderNumber} - ${x.customerName} (${formatDZD(Number(x.total??0))})`,severity:String(x.deliveryDate??'').slice(0,10)===today?'urgent' as const:'warning' as const,tab:'orders' as MainTab,targetId:x.id}));const debts=c.items.filter(x=>Number(x.outstandingBalance??0)>=30000).map(x=>({id:`debt_${x.id}`,type:'unpaid_balance' as const,title:'Créance importante en attente',description:`${x.name} doit ${formatDZD(Number(x.outstandingBalance??0))}`,severity:'warning' as const,tab:'customers' as MainTab,targetId:x.id}));if(active)setAlerts([...low,...due,...debts]);}catch{if(active)setAlerts([]);}};void load();return()=>{active=false;};},[isOpen]);
 if(!isOpen)return null;
 return <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/60 backdrop-blur-sm"><div className="w-full max-w-md bg-white dark:bg-slate-900 h-full shadow-2xl flex flex-col border-l"><div className="flex items-center justify-between px-6 py-4 border-b"><div className="flex items-center gap-2.5"><div className="p-2 rounded-xl bg-amber-50 text-amber-600"><AlertCircle className="w-5 h-5"/></div><div><h2 className="text-base font-bold">Notifications Opérationnelles</h2><p className="text-xs text-slate-500">Alertes calculées depuis les données serveur/cache</p></div></div><button type="button" onClick={onClose} className="p-2 rounded-xl"><X className="w-5 h-5"/></button></div><div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-3">{alerts.length===0?<div className="text-center py-12"><CheckCircle2 className="w-8 h-8 text-emerald-600 mx-auto mb-3"/><h4 className="text-sm font-semibold">Tout est en ordre !</h4><p className="text-xs text-slate-400 mt-1">Aucune alerte critique détectée.</p></div>:alerts.map(alert=><div key={alert.id} onClick={()=>{onNavigate(alert.tab,alert.targetId);onClose();}} className="p-4 rounded-2xl border cursor-pointer hover:shadow-md"><div className="flex items-start gap-3"><div className={`p-2 rounded-xl shrink-0 ${alert.severity==='urgent'?'bg-rose-50 text-rose-600':'bg-amber-50 text-amber-600'}`}>{alert.type==='low_stock'?<AlertTriangle className="w-4 h-4"/>:alert.type==='order_due'?<Clock className="w-4 h-4"/>:<DollarSign className="w-4 h-4"/>}</div><div className="flex-1"><div className="flex items-center justify-between gap-2"><h4 className="text-xs font-bold truncate">{alert.title}</h4><span className="text-[10px] font-semibold">{alert.severity==='urgent'?'Urgent':'À suivre'}</span></div><p className="text-xs text-slate-600 dark:text-slate-400 mt-1">{alert.description}</p><div className="flex items-center gap-1 text-[11px] font-semibold text-emerald-700 mt-2">Consulter<ArrowRight className="w-3 h-3"/></div></div></div></div>)}</div><div className="p-4 border-t text-center"><span className="text-xs text-slate-400">{alerts.length} alerte(s) active(s)</span></div></div></div>;
};
