import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,BarChart3,Camera,CheckCircle2,ChevronRight,Factory,RefreshCw,ShoppingBag,Store,Truck,Wallet} from 'lucide-react';
import {api} from '../../lib/api';
import {formatDZD} from '../../lib/utils';
import {MainTab} from '../layout/BottomNav';
import {AppLanguage} from '../../types';
import {translations} from '../../lib/i18n';
import {StatusBadge} from '../common/Badge';

type Props={onNavigate:(tab:MainTab,id?:string)=>void;onOpenQuickAction:(key:'new_order'|'quick_sale'|'new_batch'|'new_expense'|'record_payment'|'scan_code')=>void;currentLang:AppLanguage};
const today=()=>new Date().toISOString().slice(0,10); const n=(v:any)=>Number(v??0);

export const DashboardView:React.FC<Props>=({onNavigate,onOpenQuickAction,currentLang})=>{
 const t=translations[currentLang]; const [summary,setSummary]=useState<any>(); const [orders,setOrders]=useState<any[]>([]); const [customers,setCustomers]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [deliveries,setDeliveries]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const day=today();const [s,o,c,p,d]=await Promise.all([api.reportSummary(day,day),api.orders(),api.customers(),api.products(),api.deliveries()]);setSummary(s);setOrders(o.items??[]);setCustomers(c.items??[]);setProducts(p.items??[]);setDeliveries(d.items??[]);}catch(e:any){setError(e?.message??'Impossible de charger le tableau de bord');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const variants=useMemo(()=>products.flatMap(p=>(Array.isArray(p.variants)?p.variants:[]).map((v:any)=>({...v,productName:p.name}))),[products]);
 const activeOrders=useMemo(()=>orders.filter(o=>['confirmed','preparing','ready','partially_delivered'].includes(String(o.status))),[orders]);
 const todayDeliveries=useMemo(()=>deliveries.filter(d=>String(d.delivery_date??'').slice(0,10)===today()&&d.status!=='delivered'&&d.status!=='cancelled'),[deliveries]);
 const debt=useMemo(()=>customers.reduce((s,c)=>s+Math.max(0,n(c.outstanding_balance)),0),[customers]);
 const lowStock=useMemo(()=>variants.filter(v=>v.active!==false&&n(v.quantity)-n(v.reserved_quantity)<=n(v.min_stock)),[variants]);
 const priority=activeOrders.slice(0,5);
 const piecesNeeded=useMemo(()=>variants.reduce((s,v)=>Math.max(s,n(v.reserved_quantity)-n(v.quantity)),0),[variants]);
 const metrics=[['Ventes du jour',formatDZD(summary?.sales?.revenue)],['Marge brute',formatDZD(summary?.sales?.grossMargin)],['Commandes actives',activeOrders.length],['Livraisons du jour',todayDeliveries.length],['Créances clients',formatDZD(debt)],['Stock en alerte',lowStock.length]];
 return <div className="space-y-6 pb-12 animate-fade-in">
  <div className="bg-gradient-to-br from-emerald-900 via-emerald-800 to-teal-950 text-white rounded-3xl p-6 sm:p-8 shadow-xl"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6"><div><span className="inline-flex px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-700/80 text-emerald-200">Aujourd'hui · {new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</span><h1 className="text-2xl sm:text-3xl font-bold mt-3">Tableau de bord fromager</h1><p className="text-emerald-200/90 text-sm mt-1">Pilotage temps réel depuis PostgreSQL, sans chiffres fictifs.</p></div><div className="bg-emerald-950/60 p-4 rounded-2xl border border-emerald-700/50"><span className="text-xs text-emerald-300 block">Bénéfice du jour</span><strong className="text-3xl font-black">{formatDZD(summary?.netProfit)}</strong></div></div></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-xs">{error}</div>}
  <div className="flex justify-end"><button onClick={()=>void load()} className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white border text-xs font-bold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Actualiser</button></div>
  <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{metrics.map(([label,value])=><div key={String(label)} className="p-4 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><span className="text-[11px] text-slate-500 block">{label}</span><strong className="text-xl block mt-1 text-slate-900 dark:text-white">{value}</strong></div>)}</div>
  <div><div className="flex items-center justify-between mb-3"><h2 className="text-xs font-bold text-slate-500 uppercase">Actions rapides</h2></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5">{([['new_order',ShoppingBag,t.newOrder],['quick_sale',Store,t.quickSale],['new_batch',Factory,t.production],['new_expense',Wallet,t.expense],['record_payment',CheckCircle2,t.payment],['scan_code',Camera,t.scan]] as const).map(([key,Icon,label])=><button key={key} onClick={()=>onOpenQuickAction(key)} className="p-4 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 flex flex-col items-center gap-2 text-xs font-bold"><Icon className="w-5 h-5 text-emerald-700"/>{label}</button>)}</div></div>
  <div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><section className="p-5 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-slate-900 dark:text-white">Commandes prioritaires</h2><p className="text-xs text-slate-500">À préparer ou livrer</p></div><button onClick={()=>onNavigate('orders')} className="text-xs font-bold text-emerald-700 flex items-center gap-1">Voir tout<ArrowRight className="w-3.5 h-3.5"/></button></div>{priority.length?priority.map(o=><button key={o.id} onClick={()=>onNavigate('orders',o.id)} className="w-full text-left p-3 rounded-2xl bg-slate-50 dark:bg-slate-700/40 mb-2 flex items-center justify-between"><div><strong className="text-sm text-slate-900 dark:text-white">{o.number}</strong><div className="text-xs text-slate-500">{o.customer_name??'Client'} · {formatDZD(o.total)}</div></div><StatusBadge status={o.status}/></button>):<div className="py-8 text-center text-sm text-slate-500">Aucune commande prioritaire.</div>}</section>
  <section className="p-5 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-slate-900 dark:text-white">Alertes stock</h2><p className="text-xs text-slate-500">Stock disponible sous le seuil</p></div><button onClick={()=>onNavigate('products')} className="text-xs font-bold text-emerald-700 flex items-center gap-1">Produits<ChevronRight className="w-3.5 h-3.5"/></button></div>{lowStock.length?lowStock.slice(0,6).map(v=><div key={v.id} className="p-3 rounded-2xl bg-amber-50 dark:bg-amber-950/30 mb-2 flex items-center justify-between"><div><strong className="text-sm text-slate-900 dark:text-white">{v.productName??v.name}</strong><div className="text-xs text-slate-500">Disponible {n(v.quantity)-n(v.reserved_quantity)} · seuil {n(v.min_stock)}</div></div><AlertTriangle className="w-5 h-5 text-amber-600"/></div>):<div className="py-8 text-center text-sm text-emerald-700"><CheckCircle2 className="w-6 h-6 mx-auto mb-2"/>Stock dans les seuils.</div>}</section></div>
  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="p-5 rounded-2xl bg-white border"><Truck className="w-5 h-5 text-teal-700"/><strong className="block text-2xl mt-2">{todayDeliveries.length}</strong><span className="text-xs text-slate-500">Livraisons à traiter aujourd'hui</span></div><div className="p-5 rounded-2xl bg-white border"><Wallet className="w-5 h-5 text-rose-700"/><strong className="block text-2xl mt-2">{formatDZD(debt)}</strong><span className="text-xs text-slate-500">Créances clients ouvertes</span></div><div className="p-5 rounded-2xl bg-white border"><BarChart3 className="w-5 h-5 text-indigo-700"/><strong className="block text-2xl mt-2">{piecesNeeded}</strong><span className="text-xs text-slate-500">Unités supplémentaires à produire selon les réservations</span></div></div>
 </div>;
};
