import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { FileText, Search, Download, RefreshCw, Loader2 } from 'lucide-react';
import { api } from '../../lib/api';
import { CompanySettings } from '../../types';
import { getCachedCompanySettings, loadCompanySettings } from '../../lib/companySettings';
import { formatDZD, formatDate } from '../../lib/utils';
import { downloadDocumentPDF, DocumentData } from '../../lib/pdfGenerator';
import { EmptyState } from '../common/EmptyState';

type DocType='all'|'order'|'delivery'|'invoice'; type Row=Record<string,any>; type DocumentRow={id:string;number:string;type:Exclude<DocType,'all'>;typeName:string;date:string;customerName:string;total:number;raw:Row}; const num=(v:unknown)=>Number(v??0);
const mapItems=(items:any[]=[])=>items.map(item=>({designation:item.designation??item.productName??item.description??'Produit',quantity:num(item.quantity),unit:item.unit??'u',unitPrice:num(item.unitPrice??item.unit_price),total:num(item.total??item.subtotal??(num(item.quantity)*num(item.unitPrice??item.unit_price)))}));
export const DocumentsView:React.FC=()=>{
 const [docTypeFilter,setDocTypeFilter]=useState<DocType>('all');const [searchQuery,setSearchQuery]=useState('');const [orders,setOrders]=useState<Row[]>([]);const [deliveries,setDeliveries]=useState<Row[]>([]);const [invoices,setInvoices]=useState<Row[]>([]);const [settings,setSettings]=useState<CompanySettings>(()=>getCachedCompanySettings());const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const [o,d,i]=await Promise.all([api.orders(),api.deliveries(),api.invoices()]);setOrders(o.items??[]);setDeliveries(d.items??[]);setInvoices(i.items??[]);}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les documents');}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();void loadCompanySettings().then(setSettings).catch(()=>undefined);},[refresh]);
 const allDocuments=useMemo<DocumentRow[]>(()=>[...orders.map(o=>({id:String(o.id),number:String(o.number??o.orderNumber??''),type:'order' as const,typeName:'Bon de Commande (BC)',date:String(o.created_at??o.createdAt??''),customerName:String(o.customer_name??o.customerName??'Client'),total:num(o.total),raw:o})),...deliveries.map(d=>({id:String(d.id),number:String(d.number??''),type:'delivery' as const,typeName:'Bon de Livraison (BL)',date:String(d.delivery_date??d.created_at??''),customerName:String(d.customer_name??'Client'),total:num(d.total??d.order_total),raw:d})),...invoices.map(i=>({id:String(i.id),number:String(i.number??i.invoiceNumber??''),type:'invoice' as const,typeName:'Facture (FAC)',date:String(i.invoice_date??i.date??i.created_at??''),customerName:String(i.customer_name??i.customerName??'Client'),total:num(i.total),raw:i}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()),[orders,deliveries,invoices]);
 const filteredDocs=useMemo(()=>allDocuments.filter(doc=>(docTypeFilter==='all'||doc.type===docTypeFilter)&&(!searchQuery.trim()||`${doc.number} ${doc.customerName}`.toLowerCase().includes(searchQuery.trim().toLowerCase()))),[allDocuments,docTypeFilter,searchQuery]);
 const handleDownload=(doc:DocumentRow)=>{const raw=doc.raw,total=num(raw.total),paid=num(raw.paid_total??raw.paidAmount);const data:DocumentData={type:doc.type,documentNumber:doc.number,date:doc.date,customerName:doc.customerName,items:mapItems(raw.items??[]),subtotal:num(raw.subtotal??total),discount:num(raw.discount),tax:num(raw.tax),total,paidAmount:paid,balanceRemaining:Math.max(0,total-paid),notes:raw.notes,deliveryPerson:raw.delivery_person};downloadDocumentPDF(data,settings);};
 return <div className="space-y-6 pb-12 animate-fade-in"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl sm:text-2xl font-bold flex items-center gap-2"><FileText className="w-6 h-6 text-emerald-700"/><span>Documents Commerciaux & Facturation</span></h1><p className="text-xs sm:text-sm text-slate-500">BC, BL et factures alimentés directement depuis PostgreSQL.</p></div><button type="button" onClick={()=>void refresh()} disabled={loading} className="inline-flex items-center gap-2 px-3.5 py-2.5 border rounded-2xl text-xs font-bold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Actualiser</button></div><div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Rechercher par n° ou client..." className="w-full pl-10 pr-4 py-2.5 bg-white dark:bg-slate-800 border rounded-2xl text-xs"/></div><div className="flex gap-1.5 overflow-x-auto">{[['all','Tous'],['order','BC'],['delivery','BL'],['invoice','Factures']].map(([key,label])=><button key={key} type="button" onClick={()=>setDocTypeFilter(key as DocType)} className={`px-3 py-2 rounded-xl text-xs font-semibold ${docTypeFilter===key?'bg-emerald-800 text-white':'bg-white dark:bg-slate-800 border'}`}>{label}</button>)}</div></div>{error&&<div className="p-3 rounded-2xl bg-red-50 text-red-700 text-sm">{error}</div>}{loading?<div className="flex items-center justify-center py-16 text-slate-500"><Loader2 className="w-5 h-5 animate-spin mr-2"/>Chargement...</div>:filteredDocs.length===0?<EmptyState icon={FileText} title="Aucun document correspondant" description="Les documents apparaissent dès qu'ils existent dans PostgreSQL."/>:<div className="grid grid-cols-1 gap-2.5">{filteredDocs.map(doc=><div key={`${doc.id}_${doc.number}`} className="p-4 rounded-2xl bg-white dark:bg-slate-800 border flex items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><strong className="text-sm font-extrabold">{doc.number}</strong><span className="px-2 py-0.5 rounded-full text-[10px] bg-emerald-50 text-emerald-800">{doc.typeName}</span></div><span className="text-xs text-slate-500 block mt-0.5">Client : <strong>{doc.customerName}</strong> · {formatDate(doc.date)}</span></div><div className="flex items-center gap-4"><span className="font-black">{formatDZD(doc.total)}</span><button type="button" onClick={()=>handleDownload(doc)} className="px-3.5 py-2 bg-slate-100 rounded-xl font-bold flex items-center gap-1.5 text-xs"><Download className="w-3.5 h-3.5"/>PDF</button></div></div>)}</div>}</div>;
};
