import React, { useEffect, useState } from 'react';
import { Settings, Building, Printer, Database, Download, Upload, Check, ShieldCheck, Loader2 } from 'lucide-react';
import { CompanySettings, AppLanguage } from '../../types';
import { triggerHaptic } from '../../lib/utils';
import { getCachedCompanySettings, loadCompanySettings, saveCompanySettings } from '../../lib/companySettings';

interface SettingsViewProps { currentLang: AppLanguage; onLanguageChange: (lang: AppLanguage) => void; }
const API_BASE=(import.meta.env.VITE_API_URL??'/api').replace(/\/$/,'');

export const SettingsView: React.FC<SettingsViewProps> = ({ currentLang }) => {
  const [settings,setSettings]=useState<CompanySettings>(()=>getCachedCompanySettings());
  const [saving,setSaving]=useState(false);
  const [busyBackup,setBusyBackup]=useState(false);
  const [message,setMessage]=useState('');
  useEffect(()=>{void loadCompanySettings().then(setSettings).catch(()=>undefined);},[]);

  const authHeaders=(json=false)=>{const h=new Headers();if(json)h.set('Content-Type','application/json');const token=localStorage.getItem('azrnou_access_token');if(token)h.set('Authorization',`Bearer ${token}`);return h;};
  const handleSave=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setMessage('');try{const saved=await saveCompanySettings(settings);setSettings(saved);triggerHaptic();setMessage('Paramètres enregistrés sur le serveur.');}catch(err:any){setMessage(err.message||'Erreur d’enregistrement.');}finally{setSaving(false);}};

  const handleExportBackup=async()=>{setBusyBackup(true);setMessage('');try{const response=await fetch(`${API_BASE}/backup/export`,{headers:authHeaders()});const body=await response.json();if(!response.ok)throw new Error(body?.error||`API request failed (${response.status})`);const blob=new Blob([JSON.stringify(body,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`azrnou_sauvegarde_${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage('Sauvegarde serveur exportée.');}catch(err:any){setMessage(err.message||'Erreur de sauvegarde.');}finally{setBusyBackup(false);}};
  const handleImportBackup=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setBusyBackup(true);setMessage('');try{const text=await file.text();const payload=JSON.parse(text);const response=await fetch(`${API_BASE}/backup/restore`,{method:'POST',headers:authHeaders(true),body:JSON.stringify(payload)});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error||`API request failed (${response.status})`);setMessage('Sauvegarde serveur restaurée. Rechargez l’application pour refléter toutes les données.');window.setTimeout(()=>window.location.reload(),900);}catch(err:any){setMessage(err.message||'Fichier de sauvegarde invalide.');}finally{setBusyBackup(false);e.target.value='';}};

  return <div className="space-y-6 pb-12 animate-fade-in max-w-3xl">
    <div><h1 className="text-xl sm:text-2xl font-bold flex items-center gap-2"><Settings className="w-6 h-6 text-emerald-700"/>Paramètres de la Fromagerie AZRNOU</h1><p className="text-xs sm:text-sm text-slate-500 mt-0.5">Identité entreprise, documents et sauvegarde serveur.</p></div>
    {message&&<div className="p-3 rounded-2xl bg-emerald-50 text-emerald-800 text-sm">{message}</div>}
    <form onSubmit={handleSave} className="space-y-6"><div className="bg-white dark:bg-slate-800 rounded-3xl p-6 border shadow-sm space-y-4"><div className="flex items-center gap-2 pb-2 border-b"><Building className="w-5 h-5 text-emerald-700"/><h2 className="text-sm font-bold uppercase tracking-wider">Identité de l’Entreprise</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      {([['name','Raison Sociale / Nom'],['slogan','Slogan / Sous-titre'],['rc','N° RC'],['nif','NIF'],['nis','NIS'],['address','Adresse'],['phone','Téléphone'],['wilaya','Wilaya'],['email','Email'],['rib','RIP / Banque']] as Array<[keyof CompanySettings,string]>).map(([key,label])=><div key={String(key)}><label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">{label}</label><input value={String(settings[key]??'')} onChange={e=>setSettings({...settings,[key]:e.target.value})} className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700/50 border rounded-xl text-xs" /></div>)}
    </div></div><div className="bg-white dark:bg-slate-800 rounded-3xl p-6 border shadow-sm space-y-4"><div className="flex items-center gap-2 pb-2 border-b"><Printer className="w-5 h-5 text-emerald-700"/><h2 className="text-sm font-bold uppercase tracking-wider">Impression & Documents</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="block text-xs font-semibold mb-1">Format Ticket</label><select value={String(settings.printerPaperSize??'80mm')} onChange={e=>setSettings({...settings,printerPaperSize:e.target.value})} className="w-full px-3 py-2 bg-slate-50 border rounded-xl text-xs"><option value="80mm">80 mm</option><option value="58mm">58 mm</option></select></div><div><label className="block text-xs font-semibold mb-1">Monnaie</label><input disabled value="Dinar Algérien (DZD / DA)" className="w-full px-3 py-2 bg-slate-100 border rounded-xl text-xs font-bold text-slate-500"/></div></div></div><button disabled={saving} className="px-6 py-2.5 bg-emerald-800 disabled:opacity-50 text-white text-xs font-bold rounded-xl flex items-center gap-1.5">{saving?<Loader2 className="w-4 h-4 animate-spin"/>:<Check className="w-4 h-4"/>}Enregistrer les Paramètres</button></form>
    <div className="bg-white dark:bg-slate-800 rounded-3xl p-6 border shadow-sm space-y-4"><div className="flex items-center gap-2 pb-2 border-b"><Database className="w-5 h-5 text-emerald-700"/><h2 className="text-sm font-bold uppercase tracking-wider">Sauvegarde & Sécurité</h2></div><p className="text-xs text-slate-500">Les sauvegardes concernent maintenant les données réelles PostgreSQL de l’entreprise active.</p><div className="flex flex-wrap gap-3"><button type="button" disabled={busyBackup} onClick={()=>void handleExportBackup()} className="px-4 py-2 bg-slate-100 rounded-xl text-xs font-bold flex items-center gap-2"><Download className="w-4 h-4"/>Exporter la sauvegarde</button><label className="px-4 py-2 bg-slate-100 rounded-xl text-xs font-bold flex items-center gap-2 cursor-pointer"><Upload className="w-4 h-4"/>Restaurer une sauvegarde<input type="file" accept=".json" onChange={handleImportBackup} className="hidden"/></label></div><div className="text-xs text-slate-500 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-600"/>Isolation par entreprise et contrôle d’accès serveur actifs.</div></div>
  </div>;
};
